version: "3.9"

services:
  postgres:
    container_name: courses_db
    image: bitnami/postgresql
    environment:
      - POSTGRES_USER=docker
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=courses_api
    volumes:
      - ./db:/var/lib/postgresql/data
    ports:
      - 5432:5432